### ISSUE TITLE
Popup window is too narrow

### ISSUE THREAD

**Issue by icholy** [OlegGulevskyy/better-ts-errors.nvim#13]
## Description

The popup window isn't wide enough to show the entire error:

![image](https://github.com/OlegGulevskyy/better-ts-errors.nvim/assets/943597/80ac2374-c7a8-4dd7-8592-8afb1b311320)

## Steps to reproduce

1. Opened the popup for a deeply nested error
2. The error contents were cut off.

## Expected behavior

A configuration option to make the window larger.

## Environment

- Neovim version: Nightly
- better-ts-errors version: latest

**Comment by OlegGulevskyy** [comment]
Do you move Neovim window from one monitor to another maybe? I have the same when my actual nvim window changes size, the modal with error doesn't react accordingly. It gets fixed once nvim reopens.
I know it's far away from a good solution but is this your case though?

**Comment by icholy** [comment]
Yeah that's the issue. Seems like the width is being computed at startup instead of when the popup is opened.
