### ISSUE TITLE
I don't know what I did, but I see shell stuff

### ISSUE THREAD

**Issue by NullVoxPopuli** [OlegGulevskyy/better-ts-errors.nvim#4]
## Description

What I see with this plugin:
```
Error
(TS2339)
Property 'send' does not exist on type 
]0;nvp@Hephaestus: source "$SCRIPTS/bash-support/command-defaults.sh"]0;nvp@Hephaestus: source "$SCRIPTS/bash-support/config.sh"]0;nvp@Hephaestus: source "$SCRIPTS/bash-support/aliases.sh"]0;nvp@Hephaestus: source "$HOME/shell/bash/npm.sh"]0;nvp@Hephaestus: source "$HOME/shell/bash/gg.sh"]0;nvp@Hephaestus: source "$HOME/shell/bash/github-action-runner.sh"]0;nvp@Hephaestus: source "$HOME/shell/bash/git.sh"]0;nvp@Hephaestus: source "$SCRIPTS/bash-support/environment-augmentations.sh"{
  needsControls: boolean;
  splitHorizontally: boolean;
  isMinimized: boolean;
  isMaximized: boolean;
}
.

```
what my language server reports:
```
Diagnostics:
1. glint: Property 'send' does not exist on type '{ needsControls: boolean; splitHorizontally: boolean; isMinimized: boolean; isMaximized: boolean; }'. [2339]
```

## Steps to reproduce

no clue, tbh

## Expected behavior

some formatted version of what the language server reports

## Environment

- Neovim version: nighthly
- better-ts-errors version: latest

**Comment by OlegGulevskyy** [comment]
This is probably formatting of the object gone wrong, as it tries to use `prettier` and something goes wrong in there.
I think I'll add the ability to at least opt out from the JS object formatting and stick to a simple highlighting, until I get this figured out.
Sorry about that, formatting is pretty flaky right now.
I will scratch my head on what I can ask you about your setup that helps me narrow it down

**Comment by OlegGulevskyy** [comment]
Hey @NullVoxPopuli , can you please confirm for me this:
- What OS are you on?
- What terminal are you using?
- What shell are you using?
- What happens if you in your shell manually run this, do you get an output with shell stuff in it as well?
```
echo "{ id: string }" | prettier --parser typescript
```

Maybe I should add an ability to also supply your own formatting `cmd` or at least a path to a prettifier binary.. Not sure
